# processing of other variables ready for later analysis
infant <- infant %>%
    # replace missing codes with NA;
    # create factors from race and other smoking variables
    # convert bwt from ounces to grams and bin into categories
    mutate(gestation = ifelse(gestation == 999, NA, gestation),
           age = ifelse(age == 99, NA, age),
           wt = ifelse(wt == 999, NA, wt),
           race = recode_factor(race,
                                `6` = "Latino",
                                `7` = "Black",
                                `8` = "Asian",
                                `9` = "Mixed",
                                .default = "White"),
           time = recode_factor(time,
                                `0` = "never smoked",
                                `1` = "still smokes",
                                `2` = "during current preg",
                                `3` = "within 1 yr",
                                `4` = "1 to 2 yrs ago",
                                `5` = "2 to 3 yrs ago",
                                `6` = "3 to 4 yrs ago",
                                `7` = "5 to 9 yrs ago",
                                `8` = "10+ yrs ago",
                                `9` = "quit and don't know"),
           number = recode_factor(number,
                                  `0` = "never",
                                  `1` = "1-4",
                                  `2` = "5-9",
                                  `3` = "10-14",
                                  `4` = "15-19",
                                  `5` = "20-29",
                                  `6` = "30-39",
                                  `7` = "40-60",
                                  `8` = "60+",
                                  `9` = "smoke but don't know"),
           bwt_cat = cut(bwt * 28.35,
                         c(1500, 2000, 2500, 3000, 3500, 5000),
                         dig.lab = 4))
